name: Auto Build and Deploy

on: 
  push:
    branches: [main]

jobs:
  build:
    name: start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install yarn
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn run deploy